version: '3'
services:
  dante_all_networks:
    build:
      context: .
      args:
        with_users: 'true'
        all_networks: 'true'
    ports:
      - "1080:1080"
    restart: unless-stopped
    tmpfs: /tmp
    read_only: true
